/*
TRIGGERS - STORED PROCEDURES
*/

/*
CREATE OR REPLACE TRIGGER T1234 
AFTER INSERT OR UPDATE OR DELETE ON EMP FOR EACH ROW

BEGIN
IF INSERTING THEN DBMS_OUTPUT.PUT_LINE('VALUES ARE INSERTED');
ELSIF UPDATING THEN DBMS_OUTPUT.PUT_LINE('VALUES ARE UPDATED');
ELSE
DBMS_OUTPUT.PUT_LINE('VALUES ARE DELETED');
END IF;
END


CREATE OR REPLACE TRIGGER T12345 
BEFORE INSERT OR UPDATE OR DELETE ON EMP FOR EACH ROW

BEGIN
IF INSERTING THEN DBMS_OUTPUT.PUT_LINE('VALUES ARE INSERTED');
ELSIF UPDATING THEN DBMS_OUTPUT.PUT_LINE('VALUES ARE UPDATED');
ELSE
DBMS_OUTPUT.PUT_LINE('VALUES ARE DELETED');
END IF;
END

*/

INSERT INTO EMP VALUES (23, 25000);

