--Author SRI.JSB -> Version 1.0 created on Feb 15, 2023

/*


*/

--To check the existenance of Table or Views
-- "table or view does not exist"
SELECT * FROM ABCD;

CREATE TABLE AC1
(
ANUMBER NUMBER,
AMOUNT NUMBER,
NAME CHAR(20),
LOAN NUMBER
);

INSERT INTO AC1 VALUES(1,2000,'ABC',1000);
INSERT INTO AC1 VALUES(2,3000,'ABC',200);
INSERT INTO AC1 VALUES(3,5000,'ABC',8000);

DESCRIBE AC1;
SELECT * FROM AC1;

CREATE VIEW MYV1 AS SELECT ANUMBER, LOAN FROM AC1;
CREATE VIEW MYV2 AS SELECT NAME, AMOUNT FROM AC1;

SELECT * FROM MYV1;
SELECT * FROM MYV2;

CREATE OR REPLACE VIEW MYV3 AS SELECT NAME, LOAN FROM AC1;

CREATE OR REPLACE VIEW MYV4 AS SELECT NAME, LOAN FROM AC1 WITH READ ONLY;

INSERT INTO MYV1 VALUES(10,10000);

--Read only view
--Error: virtual column not allowed here
INSERT INTO MYV4 VALUES('BCD',5000);


CREATE TABLE SALARY
(
EMPID NUMBER,
DEPARTMENT CHAR(20),
SALARY NUMBER,
AGE NUMBER
);

INSERT INTO SALARY VALUES(1,'CSE',9000,21);
INSERT INTO SALARY VALUES(2,'ECE',10000,21);
INSERT INTO SALARY VALUES(3,'CIVIL',5000,22);
INSERT INTO SALARY VALUES(4,'CSE',6000,22);
INSERT INTO SALARY VALUES(5,'ECE',7000,33);
INSERT INTO SALARY VALUES(6,'CIVIL',8000,33);


SELECT AGE, AVG(SALARY) FROM SALARY GROUP BY AGE;
SELECT DEPARTMENT, AVG(SALARY) FROM SALARY GROUP BY DEPARTMENT;



