--Author SRI.JSB -> Version 1.0 created on Feb 17, 2023

/*


*/

CREATE TABLE CUSTOMER(ID NUMBER(10),NAME VARCHAR2(10),AGE NUMBER(10),ADDRESS VARCHAR2(10),SALARY NUMBER(10));

INSERT INTO CUSTOMER VALUES(1,'Ramesh',32,'Ahmedabad',2000);
INSERT INTO CUSTOMER VALUES(2,'Khilan',25,'delhi',2500);
INSERT INTO CUSTOMER VALUES(3,'Suraj',56,'chandigarh',6000);
INSERT INTO CUSTOMER VALUES(4,'Nish',45,'Ludhiana',3000);
INSERT INTO CUSTOMER VALUES(5,'Anu',48,'Mumbai',12000);

--

CREATE TABLE ORDER1 (OID NUMBER(10), ODATE DATE, CUSTOMER_ID NUMBER(10),AMOUNT NUMBER(10));
INSERT INTO ORDER1 VALUES(105,'28-oct-2014',1,1500);
INSERT INTO ORDER1 VALUES(104,'26-mar-2015',3,11500);
INSERT INTO ORDER1 VALUES(108,'28-oct-2016',4,15500);

--set operators

CREATE TABLE EMPLOYEE1(FNAME VARCHAR2(10),LNAME VARCHAR2(10),
EMPID NUMBER(10),LOC VARCHAR2(10),SALARY NUMBER(10));

INSERT INTO EMPLOYEE1 VALUES('Ram','Sinha',1,'ldh',23400);
INSERT INTO EMPLOYEE1 VALUES('Sham','Sinha',2,'chd',26400);
INSERT INTO EMPLOYEE1 VALUES('Sham','Sinha',3,'chd',26400);
INSERT INTO EMPLOYEE1 VALUES('Sham','Sinha',4,'chd',26400);

CREATE TABLE EMP_PER(NAME VARCHAR2(10),EMPID NUMBER(10));
INSERT INTO EMP_PER VALUES('SHam',2);
INSERT INTO EMP_PER VALUES('Hatim',24);
INSERT INTO EMP_PER VALUES('Alok',52);

SELECT * FROM EMPLOYEE1;
SELECT * FROM EMP_PER;

--UNION OPERATOR
SELECT EMPID FROM EMPLOYEE1 UNION SELECT EMPID FROM EMP_PER;

--UNION ALL
SELECT EMPID FROM EMPLOYEE1 UNION ALL SELECT EMPID FROM EMP_PER;

--INTERSECTION
SELECT EMPID FROM EMPLOYEE1 INTERSECT SELECT EMPID FROM EMP_PER;

--DIFFERENCE
SELECT EMPID FROM EMPLOYEE1 MINUS SELECT EMPID FROM EMP_PER;
SELECT EMPID FROM EMP_PER MINUS SELECT EMPID FROM EMPLOYEE1;

--USING DUAL TABLE
SELECT * FROM DUAL;
SELECT 1 FROM DUAL UNION SELECT 2 FROM DUAL UNION SELECT 3 FROM DUAL;

--CREATE TABLE UNIONTABLE1 AS SELECT 1 FROM DUAL UNION SELECT 2 FROM DUAL UNION SELECT 3 FROM DUAL;





