--Author SRI.JSB -> Version 1.0 created on Feb 02, 2023

SELECT * FROM STUDENT;

CREATE TABLE S1 AS SELECT * FROM STUDENT;

SELECT * FROM S1;

SELECT NAME || ROLL_NUMBER AS INFO FROM S1;

SELECT REG_NUMBER || ROLL_NUMBER ID, NAME || CITY INFO FROM S1;

SELECT REG_NUMBER PREV, REG_NUMBER+10 NEW FROM S1 /*comment*/;


SELECT 2+2 FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT * FROM DUAL;


SELECT * FROM S1;

ALTER TABLE S1 ADD (FEES NUMBER);
ALTER TABLE S1 ADD (PIN NUMBER);

ALTER TABLE S1 DROP (PIN);
ALTER TABLE S1 DROP COLUMN PIN;

DELETE FROM S1 WHERE REG_NUMBER = 4;

ALTER TABLE S1 MODIFY (FEES VARCHAR(20));

DESCRIBE S1;

ALTER TABLE S1 MODIFY (NAME NUMBER);
ALTER TABLE S1 MODIFY (NAME VARCHAR2(20));

ALTER TABLE S1 MODIFY (REG_NUMBER VARCHAR2(20));

ALTER TABLE S1 RENAME COLUMN ROLL_NUMBER TO ID;

ALTER TABLE S1 ADD (MARKS NUMBER, GRADE CHAR());

ALTER TABLE S1 MODIFY (GRADE CHAR(2));

SELECT * FROM S1;

RENAME S1 TO S11;

SELECT * FROM S11;



/* Update command */

UPDATE S11 SET MARKS = 90 WHERE REG_NUMBER = 2;

SELECT * FROM S11;

ALTER TABLE S11 MODIFY (NAME CHAR(20));


UPDATE S11 SET GRADE = 'A' WHERE REG_NUMBER = 1;
UPDATE S11 SET GRADE = 'A' WHERE NAME = 'C';

SELECT ROWID, ROWNUM, ID, NAME FROM S11 /*HIDDEN COLUMN ROWID, ROWNUM*/;



/* LOGICAL OPERATORS */

SELECT * FROM S11 WHERE GRADE = 'A' AND CITY = 'c';
SELECT * FROM S11 WHERE GRADE = 'A' OR CITY = 'c';
SELECT * FROM S11 WHERE CITY IN ('a', 'd', 'f', 'k');
SELECT * FROM S11 WHERE CITY NOT IN ('a', 'd', 'f', 'k');
SELECT * FROM S11 WHERE GRADE = 'A' AND CITY = 'c' OR MARKS = 90;

