--Author SRI.JSB -> Version 1.0 created on Feb 16, 2023

/*


*/

CREATE TABLE SALARY
(
EMPID NUMBER,
DEPARTMENT CHAR(20),
SALARY NUMBER,
AGE NUMBER
);

RENAME SALARY TO INCOME1;

INSERT INTO INCOME1 VALUES(1,'CSE',9000,21);
INSERT INTO INCOME1 VALUES(2,'ECE',10000,21);
INSERT INTO INCOME1 VALUES(3,'CIVIL',5000,22);
INSERT INTO INCOME1 VALUES(4,'CSE',6000,22);
INSERT INTO INCOME1 VALUES(5,'ECE',7000,33);
INSERT INTO INCOME1 VALUES(6,'CIVIL',8000,33);
INSERT INTO INCOME1 VALUES(10,'CSE',1000,21);

SELECT * FROM INCOME1;

SELECT AGE, SALARY FROM INCOME1;
SELECT AGE, AVG(SALARY) FROM INCOME1 GROUP BY AGE;

SELECT DEPARTMENT, AVG(SALARY) FROM INCOME1 GROUP BY DEPARTMENT;


SELECT AGE, AVG(SALARY) FROM INCOME1 GROUP BY WHERE AGE>21;

SELECT AGE, AVG(SALARY) FROM INCOME1 GROUP BY AGE HAVING AGE>21;

SELECT AGE, EMPID, AVG(SALARY) FROM INCOME1 WHERE EMPID >2;

--TO GROPU BY 
SELECT AGE, EMPID, AVG(SALARY) FROM INCOME1 GROUP BY AGE,EMPID HAVING AGE>21;
SELECT AGE, EMPID, AVG(SALARY) FROM INCOME1 WHERE EMPID >3 GROUP BY AGE,EMPID HAVING AGE>21;

SELECT AGE, EMPID, AVG(SALARY) FROM INCOME1 WHERE EMPID >3 GROUP BY AGE,EMPID HAVING AGE>21 ORDER BY EMPID;

SELECT AGE, EMPID, MAX(SALARY) FROM INCOME1 GROUP BY AGE, EMPID HAVING AGE>21;

SELECT DEPARTMENT, AGE, EMPID, MAX(SALARY) FROM INCOME1 GROUP BY AGE, EMPID, DEPARTMENT HAVING AGE>21;

SELECT DEPARTMENT, AGE, EMPID, MAX(SALARY) FROM INCOME1 GROUP BY AGE, EMPID, DEPARTMENT HAVING AGE>21 AND EMPID >5;

--NEXT PART
SELECT AVG(SALARY) FROM INCOME1 GROUP BY SALARY;
SELECT AVG(SALARY) FROM INCOME1 GROUP BY AGE;

SELECT DEPARTMENT, AVG(SALARY) FROM INCOME1 GROUP BY AGE, DEPARTMENT ORDER BY AGE;

--NEXT PART
SELECT DEPARTMENT, AGE, EMPID, MAX(SALARY) FROM INCOME1 GROUP BY AGE, EMPID, DEPARTMENT HAVING AVG(SALARY)>8000 ORDER BY AGE;


--NEXT TOPIC
CREATE TABLE GUESTLECTURE
(
LID NUMBER,
NAME CHAR(20),
CONSTRAINT GL11 PRIMARY KEY (LID)
);

INSERT INTO GUESTLECTURE VALUES(1,'A');

--TO DISABLE THE CONSTRAINTS
ALTER TABLE GUESTLECTURE DISABLE CONSTRAINT GL11;


ALTER TABLE GUESTLECTURE ENABLE CONSTRAINT GL11;

--TO DELETE THE ROWS WITH PER
DELETE FROM GUESTLECTURE WHERE LID=1;

ALTER TABLE GUESTLECTURE ENABLE CONSTRAINT GL11;

--TO DROP THE PRIMARY KEY
ALTER TABLE GUESTLECTURE DROP PRIMARY KEY;

--TO ADD PRIMARY KEY
ALTER TABLE GUESTLECTURE ADD PRIMARY KEY (LID);

ALTER TABLE GUESTLECTURE ADD CONSTRAINT GL12 UNIQUE (LID);


