--Author SRI.JSB -> Version 1.0 created on Feb 01, 2023

DESCRIBE STUDENT;

CREATE TABLE ST12 AS SELECT * FROM STUDENT;
CREATE TABLE ST13 AS SELECT * FROM STUDENT;
CREATE TABLE ST14 AS SELECT * FROM STUDENT;

SELECT * FROM ST14;
SELECT * FROM STUDENT WHERE NAME ='ABC';
SELECT * FROM STUDENT WHERE AGE=20;
SELECT * FROM STUDENT WHERE ROLL_NO='a100';
SELECT * FROM STUDENT WHERE FEE=100000;

SELECT * FROM STUDENT WHERE NAME IS NULL;
SELECT * FROM STUDENT WHERE AGE IS NULL;
SELECT * FROM STUDENT WHERE FEE IS NULL;
SELECT * FROM STUDENT WHERE NAME IS NULL;
SELECT * FROM STUDENT WHERE ROLL_NO IS NULL;

SELECT * FROM STUDENT;

DELETE FROM ST12 WHERE NAME = 'CDE';
DELETE FROM ST12;

SELECT * FROM ST13;

TRUNCATE TABLE ST13;
DESC ST13;

SELECT * FROM ST14;

DROP TABLE ST12;
DROP TABLE ST13;
DROP TABLE ST14;

