CREATE TABLE E11
(

NAME CHAR(20),
EMPID NUMBER,
SALARY NUMBER

);

INSERT INTO E11 VALUES ('ABC',1,10000);
INSERT INTO E11 VALUES ('BCD',2,20000);
INSERT INTO E11 VALUES ('CDE',3,50000);
INSERT INTO E11 VALUES ('DEF',4,80000);
INSERT INTO E11 VALUES ('FGH',5,NULL);

INSERT INTO E11 VALUES ('GHI',6,70000);
INSERT INTO E11 VALUES ('GHI',6,70000);
INSERT INTO E11 VALUES ('GHI',6,70000);


SELECT * FROM E11;

SELECT COUNT(SALARY) FROM E11;

--To find total ocunt of the rows in the table
SELECT COUNT(*) FROM E11;

SELECT AVG(SALARY) FROM E11;
SELECT MAX(SALARY) FROM E11;
SELECT MIN(SALARY) FROM E11;
SELECT SUM(SALARY) FROM E11;

--To Show only the distinc values of rows
SELECT DISTINCT(SALARY) FROM E11;

SELECT DISTINCT SALARY FROM E11;

--To count the distinct values
SELECT COUNT(DISTINCT SALARY) FROM E11;

--To order the column values in Ascending order using ORDRE BY 
--Default order is ascending
SELECT * FROM E11 ORDER BY SALARY;

SELECT * FROM E11 ORDER BY SALARY, EMPID;

SELECT * FROM E11 ORDER BY EMPID;

--SORT USING DESCENDING ORDER BY MENTIONING 'DESC'
--SOMETIMES DESC -> CONSIDERED DESCRIBE
SELECT * FROM E11 ORDER BY SALARY DESC;

--TO SORT BY THE COLUMN NUMBERS INSTEAD OF COLUMN NAMES
SELECT * FROM E11 ORDER BY 3;

SELECT * FROM E11 ORDER BY 1;

