--Author SRI.JSB -> Version 1.0 created on Feb 09, 2023

--SELECT * FROM E11;

--SYNTAX 1 FOR CREATING PRIMARY KEY
CREATE TABLE ACCOUNTS
(
REG NUMBER PRIMARY KEY,
NAME CHAR(50),
AGE NUMBER
);

DESCRIBE ACCOUNTS

--INSERT INTO ACCOUNTS VALUES(NULL,'ABC',22);
INSERT INTO ACCOUNTS VALUES(1,'ABC',18);
INSERT INTO ACCOUNTS VALUES(10,'JKL',25);
INSERT INTO ACCOUNTS VALUES(101,'MNO',10);

CREATE TABLE A1 AS SELECT * FROM ACCOUNTS;

SELECT * FROM A1;
DROP TABLE A1;

--NO DUPLICATE VALUES FOR PRIMARY KEY COLUMN IS NOT ALLOWED
INSERT INTO ACCOUNTS VALUES(1,'ABC',18);

--NO NULL VALUES ARE ALLOWED FOR P.K
INSERT INTO ACCOUNTS VALUES(NULL,'BCD',22);


--A TABLE CANNOT HAVE 2 PRIMARY KEYS

CREATE TABLE ACCOUNTS1
(
REG NUMBER PRIMARY KEY,
NAME CHAR(50),
AGE NUMBER PRIMARY KEY,
);

--sYNTAX 2 FOR CREATING PRIMARY KEY
--NOTE: WHITE SPACE ARE NOT SENSITIVE BETWEEN KEYS AND ()

--COMPOSITE P.K - MULTIPLE COLUMNS CAN BE ADDED AS PRIMARY KEY
CREATE TABLE ACCOUNTS31
(
REG NUMBER,
NAME CHAR(50),
AGE NUMBER,
PRIMARY KEY(REG,AGE) --PRIMARY KEY (REG)
);

DESCRIBE ACCOUNTS31;

INSERT INTO ACCOUNTS31 VALUES(1,'ABC',18);
INSERT INTO ACCOUNTS31 VALUES(1,'ABC',18); --UNIQUE CONSTRAINT VIOLATED
INSERT INTO ACCOUNTS31 VALUES(1,'JKL',18);
INSERT INTO ACCOUNTS31 VALUES(2,'ABC',18);
INSERT INTO ACCOUNTS31 VALUES(2,'ABC',22);
INSERT INTO ACCOUNTS31 VALUES(101,'MNO',10);

--SYNTAX 3 FOR PRIMARY KEY
--USER DEFINED CONSTRAINTS - MYC1 'MYCONSTRAINT1'
CREATE TABLE ACCOUNTS32
(
REG NUMBER,
NAME CHAR(50),
AGE NUMBER,
CONSTRAINT MYC1 PRIMARY KEY(REG)
);

--USER DEFINED CONSTRAINTS - MYC2 'MYCONSTRAINT2'
CREATE TABLE ACCOUNTS33
(
REG NUMBER,
NAME CHAR(50),
AGE NUMBER,
CONSTRAINT MYC2 PRIMARY KEY(REG,AGE)
);

/*
UNIQUE KEYS
--FOR UNIQUE KEYS - USE ONLY 'UNIQUE'
*/
--SYNTAX 1
CREATE TABLE ACCOUNTS50
(
REG NUMBER UNIQUE,
NAME CHAR(50),
AGE NUMBER
);

INSERT INTO ACCOUNTS50 VALUES(1,'ABC',18);
INSERT INTO ACCOUNTS50 VALUES(1,'ABC',18); --UNIQUE CONSTRAINT VIOLATED
INSERT INTO ACCOUNTS50 VALUES(NULL,'JKL',18);
INSERT INTO ACCOUNTS50 VALUES(2,'ABC',18);
INSERT INTO ACCOUNTS50 VALUES(2,'ABC',22);
INSERT INTO ACCOUNTS50 VALUES(101,'MNO',10);

--SYNTAX 2
CREATE TABLE ACCOUNTS51
(
REG NUMBER UNIQUE,
NAME CHAR(50),
AGE NUMBER UNIQUE
--UNIQUE (REG,AGE)
);

DESCRIBE ACCOUNTS51;
DROP TABLE ACCOUNTS51;


INSERT INTO ACCOUNTS51 VALUES(1,'ABC',18);
INSERT INTO ACCOUNTS51 VALUES(2,'DEF',18); --UNIQUE CONSTRAINT VIOLATED

--SYNTAX 2
CREATE TABLE ACCOUNTS52
(
REG NUMBER,
NAME CHAR(50),
AGE NUMBER,
UNIQUE (REG,AGE)
);

INSERT INTO ACCOUNTS52 VALUES(1,'ABC',18);
INSERT INTO ACCOUNTS52 VALUES(2,'DEF',18); --UNIQUE CONSTRAINT VIOLATED

SELECT * FROM ACCOUNTS52

--SYNTAX 3
CREATE TABLE ACCOUNTS53
(
REG NUMBER,
NAME CHAR(50),
AGE NUMBER,
CONTRAINT MYC3 UNIQUE (REG,AGE)
);

/*
FOREIGN KEY CONSTRAINTS

*/

SELECT * FROM ACCOUNTS;
DESCRIBE ACCOUNTS;

--CREATE FOREIGN KEY USING REFERNECES
CREATE TABLE PAYMENTS
(
RN NUMBER REFERENCES ACCOUNTS, --ACCOUNTS(REG) --IF WE NEED TO SPECIFY THE COLUMN NAME
AMOUNT NUMBER,
BALANCE FLOAT
);

DESCRIBE PAYMENTS;
SELECT * FROM PAYMENTS;

INSERT INTO PAYMENTS VALUES(1,10000,1000);
-- INTEGRITY CONSTRAINT VIOLATED - PARENT KEY NOT FOUND
INSERT INTO PAYMENTS VALUES(2,10000,1000);
INSERT INTO PAYMENTS VALUES(10,50000,500);

DELETE FROM ACCOUNTS WHERE REG=1;
DELETE FROM ACCOUNTS WHERE REG=101;

INSERT INTO PAYMENTS VALUES(NULL,20000,200);


CREATE TABLE T1234
(
REG NUMBER NOT NULL,
AGE NUMBER
);

INSERT INTO T1234 VALUES(NULL,22); --CANNOT INSERT NULL INTO TABLE



