--Author SRI.JSB -> Version 1.0 created on Feb 03, 2023

CREATE TABLE PROFESSOR
(
NAME CHAR(35),
PRO_ID VARCHAR2(34),
AGE NUMBER,
SALARY NUMBER,
ADDRESS VARCHAR(100)
);

SELECT * FROM PROFESSOR;

INSERT INTO PROFESSOR VALUES('JASSY','123',20,10000,'USA');
INSERT INTO PROFESSOR VALUES('DANNY','456',21,200000,'ISRAEL');
INSERT INTO PROFESSOR VALUES('ALYSSA','789',22,550000,'SWIZZ');
INSERT INTO PROFESSOR VALUES('BRANDON',' ',22,123000,'ITALY');
INSERT INTO PROFESSOR VALUES('ROSALIN','786',19,NULL,'JAPAN');

/*the name of column will be visible incase of logical operator*/
SELECT NAME FROM PROFESSOR WHERE AGE=20 AND PRO_ID=123;
SELECT NAME FROM PROFESSOR WHERE AGE=21 OR PRO_ID=456;
SELECT NAME FROM PROFESSOR WHERE AGE=20 AND PRO_ID=123;

/*this shows the name of the columns when we apply logical operator*/
SELECT * FROM PROFESSOR WHERE AGE=20 OR PRO_ID='123';
SELECT * FROM PROFESSOR WHERE AGE=20 AND PRO_ID='123';
SELECT * FROM PROFESSOR WHERE AGE=20 AND PRO_ID='123';

/*applying two logics at same time precision= notin,not,and,or*/
SELECT * FROM PROFESSOR WHERE AGE=20 AND PRO_ID='123' OR SALARY=90000;
SELECT NAME FROM PROFESSOR WHERE AGE=20 AND PRO_ID='123' AND SALARY=90000;
SELECT * FROM PROFESSOR WHERE AGE NOT IN(20);


/*for precision of logics whheere brackets take over the precision*/
SELECT NAME FROM PROFESSOR WHERE (AGE=20 AND PRO_ID='123') OR SALARY=90000;
SELECT * FROM PROFESSOR WHERE (AGE=20 AND PRO_ID='123') OR SALARY=90000;

/*writing the between condition of two values*/
SELECT * FROM PROFESSOR WHERE AGE BETWEEN 19 AND 22;
SELECT * FROM PROFESSOR WHERE AGE BETWEEN 19 AND 100;

/*logically incorrect but we can see that thesw value exist */
SELECT * FROM PROFESSOR WHERE NAME BETWEEN 'A' AND 'F';

/*comparison operator*/
SELECT * FROM PROFESSOR WHERE AGE>19;
SELECT * FROM PROFESSOR WHERE AGE<22;
SELECT * FROM PROFESSOR WHERE AGE>ANY(19,20);
SELECT * FROM PROFESSOR WHERE AGE=ANY(22);
SELECT * FROM PROFESSOR WHERE AGE>19 AND AGE<22;
SELECT * FROM PROFESSOR WHERE AGE<=ANY(22);
SELECT * FROM PROFESSOR WHERE AGE>=ANY(19);
SELECT * FROM PROFESSOR WHERE AGE>=ALL(19);


SELECT * FROM S11 WHERE GRADE = 'A' AND CITY = 'c';
SELECT * FROM S11 WHERE GRADE = 'A' OR CITY = 'c';
SELECT * FROM S11 WHERE CITY IN ('a', 'd', 'f', 'k');
SELECT * FROM S11 WHERE CITY NOT IN ('a', 'd', 'f', 'k');
SELECT * FROM S11 WHERE GRADE = 'A' AND CITY = 'c' OR MARKS = 90;