--TO ADD NEW COLUMNS INTO TABLE
ALTER TABLE S1 ADD(DOB DATE, AGE NUMBER);

--TO ADD NEW COLUMNS INTO TABLE
ALTER TABLE E1 ADD(DOB DATE, EMAIL VARCHAR2(24), SALARY NUMBER(10,2));

--TO DROP THE COLUMN FROM TABLE
ALTER TABLE S1 DROP COLUMN AGE;

--TO MODIFY THE EXISTING COLUMN DATA TYPES
ALTER TABLE E1 MODIFY EMAIL CHAR(22);

--TO RENAME THE TABLENAME OR COLUMN NAME
ALTER TABLE E2 RENAME TO E1;
ALTER TABLE E1 RENAME COLUMN SALARY TO BONUS;

